# Generated by Django 3.2 on 2021-05-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(default='admin', max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_by', models.CharField(max_length=100, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(db_index=True, max_length=2000)),
                ('description', models.CharField(db_index=True, max_length=2000)),
                ('published_at', models.DateTimeField()),
                ('url', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
